version: "3.1"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: finpro
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/1_create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql
      - ./scripts/2_insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql
