version: "3.1"
services:
  mysql01:
    container_name: mysql01
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/1_create_databases.sql:/docker-entrypoint-initdb.d/1_create_databases.sql
      - ./scripts/2_create_tables.sql:/docker-entrypoint-initdb.d/2_create_tables.sql
      - ./scripts/3_insert_data.sql:/docker-entrypoint-initdb.d/3_insert_data.sql
